### ISSUE TITLE
Type erased address type

### ISSUE THREAD

**Issue by robamu** [asynchronics/asynchronix#16]
Is there some way to get type erased variants of the address type and work with those when sending or scheduling events?

I have a struct like this

```rust
// The simulation controller processes requests and drives the simulation.
pub struct SimController {
    pub sys_clock: SystemClock,
    pub request_receiver: mpsc::Receiver<SimRequest>,
    pub simulation: Simulation,
    pub mgm_addr: Address<MagnetometerModel>,
    pub pcdu_addr: Address<PcduModel>,
}

```

where I need to keep the address handles for each distinct model type to send or schedule events to these devices. I think if I scale up my simulation to a large number of devices, the number of fields in this struct, and the effort to always update the SimController construction might get unwieldy. A type-erased variant would allow something like `HashMap<ModelId, Address>` to be used. But there are probably technical limitations due to the way generics are used here?

**Comment by sbarral** [comment]
I have something very similar already in my (for now private) experiment with RPC, but this is all very much in flux. What I have is actually more general, like an `Output<T>`, i.e. it is only bound to the event type and can be connected to multiple models, but instead of generating a future when "sending" an event, it generates a deferred `Action` that can be scheduled or processed immediately using something like `Simulation::schedule_action(deadline, action)`.

I could publish this WIP if you want, but I would not recommend using it before it stabilizes.

As a stopgap measure, you could define a trait to abstract over that, something like:

```rust
trait EventSender<T> {
    fn schedule_event(simulation: &mut Simulation, event: T) -> -> Result<(), SchedulingError>;
    fn schedule_keyed_event(simulation: &mut Simulation, event: T) -> -> Result<EventKey, SchedulingError>;
    ...
}
```
and then implement it on a parametrized type that stores the `Address` and the relevant `InputFn` closure for the target model.
Not super-elegant but it should work...

In any case, I'd keep this issue open until the WIP solution arrives officially in v0.3.

**Comment by robamu** [comment]
If there is already something WIP, I am okay with waiting 👍  The complexity if still manageable for me.

**Comment by sbarral** [comment]
Closed by #24 with the addition of the `Source` port type.

**Comment by robamu** [comment]
Hi @sbarral !

I am trying to update my project to nexosim 0.3.1 and I am also looking into integrating this new Source port type. Are there any examples?

**Comment by robamu** [comment]
To be honest, maybe the current way is still the best. Even when using `EventSource`, the source is tied to the input type `T`, so for example, I think I'd still need two event sources to process input events for something like my PCDU model which has two input ports with different input types

**Comment by sbarral** [comment]
Just curious: how would a type-erased `EventSource` work and why would you want it? We do have internally a type-erased event source, but this is only relevant for (de)serialization and it is too idiosyncratic to be exposed publicly (it assumes CBOR as serialization format).

**Comment by robamu** [comment]
It was just a thought I had about how I would do the scaling of the simulation to a large number of devices, but this is not relevant for me right now because the complexity is manageable.

I mentioned the `HashMap<DeviceId, Address>` type, which would not work without type erasure.  However, I can see the advantage of the explicit types required for event processing. I could still use `Vec<Address<MyExampleModel>` if I had multiple devices of the same type, and I can group my devices in substructures, so the initial though I had that this structure could get unwieldy is not that much of an problem at all I think

**Comment by sbarral** [comment]
Do I understand that such type-erased event source would take an `Any` type and return an error if it does not match the actual type? It should be very easy to build this on top of the current `EventSource<T>`, but I am not sure it is of sufficient general interest to provide it within NeXosim...

**Comment by robamu** [comment]
I suppose it could work like that. As I said, I do not really need it and the most important question is probably whether it could make large scale simulations easier to write/read/maintain.
