### ISSUE TITLE
A question about the mt_executor logic

### ISSUE THREAD

**Issue by nullchinchilla** [asynchronics/asynchronix#40]
I am trying to port the overall design of `asynchronix` to my own executor `smolscale`, and something I'm struggling with is that this assert here non-deterministically fails: https://github.com/geph-official/smolscale/blob/4bb45b79fbac877919cda2e2ffbbe06a77eb22ee/src/pool_manager.rs#L153

I guess this is not the most appropriate place to ask it, but I don't quite understand what sort of logic error in the rest of the code is this assert guarding against? How would I start to debug my code? I basically attempted to follow asynchornix's logic as closely as possible and I don't see why this assert would fail.

**Comment by sbarral** [comment]
I had a quick look at your code (`asynchronix` branch) but couldn't see this method being called so I can't really have a guess at to what is wrong.

As you probably inferred, the assert only checks that the worker to be de-activated is indeed active. For what it's worth, I don't recall this assert ever being triggered in asynchronix so I suspect the problem is in the code that differs from asynchronix. I haven't touched this part of the code for a long time, but here are 2 things worth looking at:

- the bit flag should always be set **before** the worker with this ID is unparked,
- there may be subtle synchronization issues; when in doubt use `activate_worker` instead of `activate_worker_relaxed`.


Hope this helps!

If not, the best is probably that you open an issue on `smolscale` and notify me in the issue description, but bear in mind that I will only have time to help out in the second half of next week.

**Comment by nullchinchilla** [comment]
https://github.com/geph-official/smolscale/issues/5

Thanks! The logic that calls that part of the code is in `new_executor.rs` and is actually basically copy-and-pasted from asynchronix, so I was a little confused.
